apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website-app
  template:
    metadata:
      labels:
        app: website-app
    spec:
      containers:
        - name: website-app
          image: amitksunbeam/website-app:2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'

---
apiVersion: v1
kind: Service
metadata:
  name: website-app
spec:
  selector:
    app: website-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
